Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# run the downloading script
pdd.run(args)
------------------

----- stderr -----
WARNING:root:Error getting the token - check user name and password
Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_access.py", line 168, in list_tokens
    tokens.append(x['access_token'])
TypeError: string indices must be integers
----- stderr -----
WARNING:root:Error getting the token - check user name and password
Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_access.py", line 128, in create_token
    token = response_content['access_token']
KeyError: 'access_token'
----- stderr -----
WARNING:root:Error getting the token - check user name and password
Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_access.py", line 128, in create_token
    token = response_content['access_token']
KeyError: 'access_token'
----- stderr -----
WARNING:root:Error getting the token - check user name and password
Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_access.py", line 128, in create_token
    token = response_content['access_token']
KeyError: 'access_token'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRetryError[0m                                Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m [38;5;66;03m# run the downloading script[39;00m
[0;32m----> 2[0m [43mpdd[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43margs[49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_data_downloader.py:136[0m, in [0;36mrun[0;34m(args)[0m
[1;32m    133[0m     exit([38;5;241m1[39m)
[1;32m    135[0m pa[38;5;241m.[39msetup_earthdata_login_auth(edl)
[0;32m--> 136[0m token [38;5;241m=[39m [43mpa[49m[38;5;241;43m.[39;49m[43mget_token[49m[43m([49m[43mtoken_url[49m[43m)[49m
[1;32m    138[0m provider [38;5;241m=[39m args[38;5;241m.[39mprovider
[1;32m    139[0m start_date_time [38;5;241m=[39m args[38;5;241m.[39mstartDate

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/subscriber/podaac_access.py:102[0m, in [0;36mget_token[0;34m(url)[0m
[1;32m    100[0m tokens [38;5;241m=[39m list_tokens(url)
[1;32m    101[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(tokens) [38;5;241m==[39m [38;5;241m0[39m :
[0;32m--> 102[0m     [38;5;28;01mreturn[39;00m [43mcreate_token[49m[43m([49m[43murl[49m[43m)[49m
[1;32m    103[0m [38;5;28;01melse[39;00m:
[1;32m    104[0m     [38;5;28;01mreturn[39;00m tokens[[38;5;241m0[39m]

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/tenacity/__init__.py:289[0m, in [0;36mBaseRetrying.wraps.<locals>.wrapped_f[0;34m(*args, **kw)[0m
[1;32m    287[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(f)
[1;32m    288[0m [38;5;28;01mdef[39;00m [38;5;21mwrapped_f[39m([38;5;241m*[39margs: t[38;5;241m.[39mAny, [38;5;241m*[39m[38;5;241m*[39mkw: t[38;5;241m.[39mAny) [38;5;241m-[39m[38;5;241m>[39m t[38;5;241m.[39mAny:
[0;32m--> 289[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkw[49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/tenacity/__init__.py:379[0m, in [0;36mRetrying.__call__[0;34m(self, fn, *args, **kwargs)[0m
[1;32m    377[0m retry_state [38;5;241m=[39m RetryCallState(retry_object[38;5;241m=[39m[38;5;28mself[39m, fn[38;5;241m=[39mfn, args[38;5;241m=[39margs, kwargs[38;5;241m=[39mkwargs)
[1;32m    378[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m--> 379[0m     do [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43miter[49m[43m([49m[43mretry_state[49m[38;5;241;43m=[39;49m[43mretry_state[49m[43m)[49m
[1;32m    380[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(do, DoAttempt):
[1;32m    381[0m         [38;5;28;01mtry[39;00m:

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/tenacity/__init__.py:325[0m, in [0;36mBaseRetrying.iter[0;34m(self, retry_state)[0m
[1;32m    323[0m     retry_exc [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mretry_error_cls(fut)
[1;32m    324[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mreraise:
[0;32m--> 325[0m         [38;5;28;01mraise[39;00m [43mretry_exc[49m[38;5;241;43m.[39;49m[43mreraise[49m[43m([49m[43m)[49m
[1;32m    326[0m     [38;5;28;01mraise[39;00m retry_exc [38;5;28;01mfrom[39;00m [38;5;21;01mfut[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexception[39;00m()
[1;32m    328[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mwait:

File [0;32m~/opt/anaconda3/envs/ms274/lib/python3.10/site-packages/tenacity/__init__.py:159[0m, in [0;36mRetryError.reraise[0;34m(self)[0m
[1;32m    157[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mlast_attempt[38;5;241m.[39mfailed:
[1;32m    158[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39mlast_attempt[38;5;241m.[39mresult()
[0;32m--> 159[0m [38;5;28;01mraise[39;00m [38;5;28mself[39m

[0;31mRetryError[0m: RetryError[<Future at 0x10fb1b640 state=finished returned str>]

