Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mike/opt/anaconda3/envs/teaching/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for i in range(len(file_urls)):
    url = file_urls[i]
    
    file_name = url.split('/')[-1]
    if file_name not in os.listdir(download_folder):
    
        print('Downloading '+file_name+' (file '+str(i+1)+' of '+str(len(file_urls))+')')
    
        output_file = os.path.join(download_folder,file_name)
    
        with requests.get(url, stream=True, allow_redirects=True) as r:
            r.raise_for_status()
            with open(output_file, 'wb') as f:                   
                for chunk in r.iter_content(chunk_size=8192):   
                    f.write(chunk)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 5[0m
[1;32m      2[0m url [38;5;241m=[39m file_urls[i]
[1;32m      4[0m file_name [38;5;241m=[39m url[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m/[39m[38;5;124m'[39m)[[38;5;241m-[39m[38;5;241m1[39m]
[0;32m----> 5[0m [38;5;28;01mif[39;00m file_name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mdownload_folder[49m[43m)[49m:
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mDownloading [39m[38;5;124m'[39m[38;5;241m+[39mfile_name[38;5;241m+[39m[38;5;124m'[39m[38;5;124m (file [39m[38;5;124m'[39m[38;5;241m+[39m[38;5;28mstr[39m(i[38;5;241m+[39m[38;5;241m1[39m)[38;5;241m+[39m[38;5;124m'[39m[38;5;124m of [39m[38;5;124m'[39m[38;5;241m+[39m[38;5;28mstr[39m([38;5;28mlen[39m(file_urls))[38;5;241m+[39m[38;5;124m'[39m[38;5;124m)[39m[38;5;124m'[39m)
[1;32m      9[0m     output_file [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(download_folder,file_name)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: ''

